uploads = []
outputs = []

[[generated]]
id = "ypJNswiZIwzx7xdw3OE8t"
uri = "file://artifacts/terra-technologies/src/assets/full_lawn_restoration.png"
type = "image"
title = "full lawn restoration watercolor"
